language: ruby
rvm:
  - 2.1
gemfile:
  - Gemfile
before_install:
  - mysql -e "create database IF NOT EXISTS shinq_test;" -uroot
  - mysql -p shinq_test -e "create table queue_test (job_id varchar(255) not null) ENGINE=QUEUE;" -uroot
script: bundle exec rspec
