language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - Gemfile
before_install:
  - gem update bundler
  - mysql -e "create database IF NOT EXISTS shinq_test;" -uroot
script: bundle exec rspec
